services:
  datanode:
    image: venukumar975/datanode-app:v3
    container_name: datanode-v3
    ports:
      - "${NODE_PORT}:${NODE_PORT}"  # Maps [Host Port]:[Container Port]
    env_file:
      - .env
    restart: always