version: "3.9"

services:
  datanode:
    build:
      context: .
      dockerfile: /Dockerfile
    image: storec-datanode
    container_name: datanode-v3
    env_file:
      - ./.env
    ports:
      - "50052:50052"
    volumes:
      - storec_dn1_data:/data
    restart: always

volumes:
  storec_dn1_data: