FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY config ./config

RUN mkdir -p /data/chunks
RUN mkdir -p /data/tmp
RUN mkdir -p /logs

EXPOSE 50052

CMD ["python", "app/main.py"]