import grpc
import sys
import os
import hashlib
from pathlib import Path

# Add project root to sys.path to allow imports from proto
project_root = str(Path(__file__).resolve().parent.parent)
if project_root not in sys.path:
    sys.path.append(project_root)

from proto import namenode_pb2
from proto import namenode_pb2_grpc
from proto import common_pb2

def get_file_metadata(host='10.10.20.60', port=50051, file_name='text_file.txt'):
    address = f"{host}:{port}"
    print(f"Connecting to NameNode at {address}...")
    
    channel = grpc.insecure_channel(address)
    stub = namenode_pb2_grpc.NameNodeServiceStub(channel)
    
    print(f"\n--- Getting Metadata for {file_name} ---")
    
    metadata_request = namenode_pb2.GetFileMetadataRequest(
        file_details=common_pb2.File(
            file_name=file_name,
            file_size=1024  # Size not needed for metadata request
        )
    )
    
    try:
        metadata_response = stub.GetFileMetadata(metadata_request)
        print(f"GetFileMetadata Status: Success=True")
        print(f"File: {metadata_response.file_details.file_name}")
        print(f"File Size: {metadata_response.file_details.file_size} bytes")
        print(f"Stripe Size: {metadata_response.stripe_size} bytes")
        print(f"Data Blocks (k): {metadata_response.data_blocks_k}")
        print(f"Parity Blocks (m): {metadata_response.parity_blocks_m}")
        print(f"Number of Block Groups: {len(metadata_response.block_groups)}")
        
        # Collect all block IDs for checksum and file writing
        all_block_ids = []
        
        print("\n--- Block Groups ---")
        for i, block_group in enumerate(metadata_response.block_groups):
            print(f"Stripe ID: {block_group.stripe_id}")
            for placement in block_group.placement:
                print(f"  Block ID: {placement.block_id} -> Node: {placement.node.node_id} ({placement.node.node.hostname}:{placement.node.node.port})")
                all_block_ids.append(placement.block_id)
        
        # Generate checksum of all block IDs
        if all_block_ids:
            # Sort block IDs for consistent checksum
            sorted_block_ids = sorted(all_block_ids)
            # Create checksum string
            checksum_input = "|".join(sorted_block_ids)
            checksum = hashlib.sha256(checksum_input.encode()).hexdigest()
            
            print(f"\n--- Checksum Verification ---")
            print(f"Total Blocks Found: {len(all_block_ids)}")
            print(f"Checksum (SHA256): {checksum}")
            
            # Write block IDs to file
            output_filename = f"{file_name}_block_ids.txt"
            try:
                with open(output_filename, 'w') as f:
                    f.write(f"# Block IDs for {file_name}\n")
                    f.write(f"# Total blocks: {len(all_block_ids)}\n")
                    f.write(f"# Checksum (SHA256): {checksum}\n")
                    f.write(f"# Generated by read_client\n\n")
                    for block_id in sorted_block_ids:
                        f.write(f"{block_id}\n")
                print(f"Block IDs written to: {output_filename}")
            except Exception as e:
                print(f"Failed to write block IDs to file: {e}")
        else:
            print("\n--- Checksum Verification ---")
            print("No block IDs found!")
        
    except grpc.RpcError as e:
        print(f"RPC failed: {e.code()} - {e.details()}")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Read file metadata from NameNode.")
    parser.add_argument("--host", default="10.10.20.60", help="NameNode hostname (default: 10.10.20.60)")
    parser.add_argument("--port", default="50051", help="NameNode port (default: 50051)")
    parser.add_argument("--file", default="text_file.txt", help="File name to read metadata for (default: test_file.txt)")
    
    args = parser.parse_args()
    get_file_metadata(host=args.host, port=args.port, file_name=args.file)
