# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\x05proto\"&\n\x04Node\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"4\n\x06NodeId\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x19\n\x04node\x18\x02 \x01(\x0b\x32\x0b.proto.Node\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x04\x46ile\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_size\x18\x02 \x01(\x03\"A\n\x05\x42lock\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x12\n\ndata_bytes\x18\x02 \x01(\x0c\x12\x12\n\nblock_size\x18\x03 \x01(\x03\":\n\tPlacement\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x1b\n\x04node\x18\x02 \x01(\x0b\x32\r.proto.NodeId\"E\n\x0b\x42lockGroups\x12\x11\n\tstripe_id\x18\x01 \x01(\t\x12#\n\tplacement\x18\x02 \x03(\x0b\x32\x10.proto.Placement\"K\n\rShardMetadata\x12\x11\n\tstripe_id\x18\x01 \x01(\t\x12\x13\n\x0bshard_index\x18\x02 \x01(\x05\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\"R\n\x0eShardPlacement\x12#\n\x05shard\x18\x01 \x01(\x0b\x32\x14.proto.ShardMetadata\x12\x1b\n\x04node\x18\x02 \x01(\x0b\x32\r.proto.NodeId\"[\n\rHeartbeatInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x12\n\nused_bytes\x18\x03 \x01(\x03\x12\x12\n\nfree_bytes\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODE']._serialized_start=29
  _globals['_NODE']._serialized_end=67
  _globals['_NODEID']._serialized_start=69
  _globals['_NODEID']._serialized_end=121
  _globals['_STATUS']._serialized_start=123
  _globals['_STATUS']._serialized_end=165
  _globals['_FILE']._serialized_start=167
  _globals['_FILE']._serialized_end=211
  _globals['_BLOCK']._serialized_start=213
  _globals['_BLOCK']._serialized_end=278
  _globals['_PLACEMENT']._serialized_start=280
  _globals['_PLACEMENT']._serialized_end=338
  _globals['_BLOCKGROUPS']._serialized_start=340
  _globals['_BLOCKGROUPS']._serialized_end=409
  _globals['_SHARDMETADATA']._serialized_start=411
  _globals['_SHARDMETADATA']._serialized_end=486
  _globals['_SHARDPLACEMENT']._serialized_start=488
  _globals['_SHARDPLACEMENT']._serialized_end=570
  _globals['_HEARTBEATINFO']._serialized_start=572
  _globals['_HEARTBEATINFO']._serialized_end=663
# @@protoc_insertion_point(module_scope)
