# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12\x05proto\"9\n\x06NodeId\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"K\n\x08\x45\x43Policy\x12\x13\n\x0b\x64\x61ta_shards\x18\x01 \x01(\x05\x12\x15\n\rparity_shards\x18\x02 \x01(\x05\x12\x13\n\x0bstripe_size\x18\x03 \x01(\x05\"\x1d\n\x08StripeId\x12\x11\n\tstripe_id\x18\x01 \x01(\t\"1\n\x07ShardId\x12\x11\n\tstripe_id\x18\x01 \x01(\t\x12\x13\n\x0bshard_index\x18\x02 \x01(\x05\"K\n\rShardMetadata\x12\x11\n\tstripe_id\x18\x01 \x01(\t\x12\x13\n\x0bshard_index\x18\x02 \x01(\x05\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\"R\n\x0eShardPlacement\x12#\n\x05shard\x18\x01 \x01(\x0b\x32\x14.proto.ShardMetadata\x12\x1b\n\x04node\x18\x02 \x01(\x0b\x32\r.proto.NodeId\"W\n\tHeartbeat\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x12\n\nused_bytes\x18\x03 \x01(\x03\x12\x12\n\nfree_bytes\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEID']._serialized_start=29
  _globals['_NODEID']._serialized_end=86
  _globals['_STATUS']._serialized_start=88
  _globals['_STATUS']._serialized_end=130
  _globals['_ECPOLICY']._serialized_start=132
  _globals['_ECPOLICY']._serialized_end=207
  _globals['_STRIPEID']._serialized_start=209
  _globals['_STRIPEID']._serialized_end=238
  _globals['_SHARDID']._serialized_start=240
  _globals['_SHARDID']._serialized_end=289
  _globals['_SHARDMETADATA']._serialized_start=291
  _globals['_SHARDMETADATA']._serialized_end=366
  _globals['_SHARDPLACEMENT']._serialized_start=368
  _globals['_SHARDPLACEMENT']._serialized_end=450
  _globals['_HEARTBEAT']._serialized_start=452
  _globals['_HEARTBEAT']._serialized_end=539
# @@protoc_insertion_point(module_scope)
