# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import datanode_pb2 as proto_dot_datanode__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/datanode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteShard = channel.unary_unary(
                '/proto.DataNodeService/WriteShard',
                request_serializer=proto_dot_datanode__pb2.WriteShardRequest.SerializeToString,
                response_deserializer=proto_dot_datanode__pb2.WriteShardResponse.FromString,
                _registered_method=True)
        self.ReadShard = channel.unary_unary(
                '/proto.DataNodeService/ReadShard',
                request_serializer=proto_dot_datanode__pb2.ReadShardRequest.SerializeToString,
                response_deserializer=proto_dot_datanode__pb2.ReadShardResponse.FromString,
                _registered_method=True)
        self.DeleteShard = channel.unary_unary(
                '/proto.DataNodeService/DeleteShard',
                request_serializer=proto_dot_datanode__pb2.DeleteShardRequest.SerializeToString,
                response_deserializer=proto_dot_datanode__pb2.DeleteShardResponse.FromString,
                _registered_method=True)


class DataNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteShard': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteShard,
                    request_deserializer=proto_dot_datanode__pb2.WriteShardRequest.FromString,
                    response_serializer=proto_dot_datanode__pb2.WriteShardResponse.SerializeToString,
            ),
            'ReadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadShard,
                    request_deserializer=proto_dot_datanode__pb2.ReadShardRequest.FromString,
                    response_serializer=proto_dot_datanode__pb2.ReadShardResponse.SerializeToString,
            ),
            'DeleteShard': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteShard,
                    request_deserializer=proto_dot_datanode__pb2.DeleteShardRequest.FromString,
                    response_serializer=proto_dot_datanode__pb2.DeleteShardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.DataNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.DataNodeService/WriteShard',
            proto_dot_datanode__pb2.WriteShardRequest.SerializeToString,
            proto_dot_datanode__pb2.WriteShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.DataNodeService/ReadShard',
            proto_dot_datanode__pb2.ReadShardRequest.SerializeToString,
            proto_dot_datanode__pb2.ReadShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.DataNodeService/DeleteShard',
            proto_dot_datanode__pb2.DeleteShardRequest.SerializeToString,
            proto_dot_datanode__pb2.DeleteShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
