# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import datanode_pb2 as proto_dot_datanode__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/datanode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteBlock = channel.unary_unary(
                '/proto.DataNodeService/WriteBlock',
                request_serializer=proto_dot_datanode__pb2.WriteBlockRequest.SerializeToString,
                response_deserializer=proto_dot_datanode__pb2.WriteBlockResponse.FromString,
                _registered_method=True)
        self.ReadBlock = channel.unary_unary(
                '/proto.DataNodeService/ReadBlock',
                request_serializer=proto_dot_datanode__pb2.ReadBlockRequest.SerializeToString,
                response_deserializer=proto_dot_datanode__pb2.ReadBlockResponse.FromString,
                _registered_method=True)
        self.DeleteBlock = channel.unary_unary(
                '/proto.DataNodeService/DeleteBlock',
                request_serializer=proto_dot_datanode__pb2.DeleteBlockRequest.SerializeToString,
                response_deserializer=proto_dot_datanode__pb2.DeleteBlockResponse.FromString,
                _registered_method=True)


class DataNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteBlock(self, request, context):
        """all methods only invoked by clientfor block ops
        (block_id, data_bytes, block_size)
        (Status, NodeId, block_id)
        (Block) => (Status, NodeId, block_id)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlock(self, request, context):
        """(block_id)
        (Status, Block)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlock(self, request, context):
        """(block_id)
        (Status, NodeId, block_id)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteBlock,
                    request_deserializer=proto_dot_datanode__pb2.WriteBlockRequest.FromString,
                    response_serializer=proto_dot_datanode__pb2.WriteBlockResponse.SerializeToString,
            ),
            'ReadBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlock,
                    request_deserializer=proto_dot_datanode__pb2.ReadBlockRequest.FromString,
                    response_serializer=proto_dot_datanode__pb2.ReadBlockResponse.SerializeToString,
            ),
            'DeleteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlock,
                    request_deserializer=proto_dot_datanode__pb2.DeleteBlockRequest.FromString,
                    response_serializer=proto_dot_datanode__pb2.DeleteBlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.DataNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.DataNodeService/WriteBlock',
            proto_dot_datanode__pb2.WriteBlockRequest.SerializeToString,
            proto_dot_datanode__pb2.WriteBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.DataNodeService/ReadBlock',
            proto_dot_datanode__pb2.ReadBlockRequest.SerializeToString,
            proto_dot_datanode__pb2.ReadBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.DataNodeService/DeleteBlock',
            proto_dot_datanode__pb2.DeleteBlockRequest.SerializeToString,
            proto_dot_datanode__pb2.DeleteBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
