# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/datanode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/datanode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/datanode.proto\x12\x05proto\x1a\x12proto/common.proto\"F\n\x11WriteShardRequest\x12#\n\x05shard\x18\x01 \x01(\x0b\x32\x14.proto.ShardMetadata\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"3\n\x12WriteShardResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status\"1\n\x10ReadShardRequest\x12\x1d\n\x05shard\x18\x01 \x01(\x0b\x32\x0e.proto.ShardId\"@\n\x11ReadShardResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"3\n\x12\x44\x65leteShardRequest\x12\x1d\n\x05shard\x18\x01 \x01(\x0b\x32\x0e.proto.ShardId\"4\n\x13\x44\x65leteShardResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status2\xda\x01\n\x0f\x44\x61taNodeService\x12\x41\n\nWriteShard\x12\x18.proto.WriteShardRequest\x1a\x19.proto.WriteShardResponse\x12>\n\tReadShard\x12\x17.proto.ReadShardRequest\x1a\x18.proto.ReadShardResponse\x12\x44\n\x0b\x44\x65leteShard\x12\x19.proto.DeleteShardRequest\x1a\x1a.proto.DeleteShardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.datanode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITESHARDREQUEST']._serialized_start=51
  _globals['_WRITESHARDREQUEST']._serialized_end=121
  _globals['_WRITESHARDRESPONSE']._serialized_start=123
  _globals['_WRITESHARDRESPONSE']._serialized_end=174
  _globals['_READSHARDREQUEST']._serialized_start=176
  _globals['_READSHARDREQUEST']._serialized_end=225
  _globals['_READSHARDRESPONSE']._serialized_start=227
  _globals['_READSHARDRESPONSE']._serialized_end=291
  _globals['_DELETESHARDREQUEST']._serialized_start=293
  _globals['_DELETESHARDREQUEST']._serialized_end=344
  _globals['_DELETESHARDRESPONSE']._serialized_start=346
  _globals['_DELETESHARDRESPONSE']._serialized_end=398
  _globals['_DATANODESERVICE']._serialized_start=401
  _globals['_DATANODESERVICE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
