# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import namenode_pb2 as proto_dot_namenode__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/namenode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NameNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDataNode = channel.unary_unary(
                '/proto.NameNodeService/RegisterDataNode',
                request_serializer=proto_dot_namenode__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.AllocateBlocks = channel.unary_unary(
                '/proto.NameNodeService/AllocateBlocks',
                request_serializer=proto_dot_namenode__pb2.AllocateBlocksRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.AllocateBlocksResponse.FromString,
                _registered_method=True)
        self.CommitFile = channel.unary_unary(
                '/proto.NameNodeService/CommitFile',
                request_serializer=proto_dot_namenode__pb2.CommitFileRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.CommitFileResponse.FromString,
                _registered_method=True)
        self.GetFileMetadata = channel.unary_unary(
                '/proto.NameNodeService/GetFileMetadata',
                request_serializer=proto_dot_namenode__pb2.GetFileMetadataRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.GetFileMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/proto.NameNodeService/DeleteFile',
                request_serializer=proto_dot_namenode__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/proto.NameNodeService/SendHeartbeat',
                request_serializer=proto_dot_namenode__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/proto.NameNodeService/ListFiles',
                request_serializer=proto_dot_namenode__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class NameNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDataNode(self, request, context):
        """DataNode registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateBlocks(self, request, context):
        """invoked by client for storage targets
        namenode access record/registry
        (file_name, file_size, stripe_size, data_blocks_k, parity_blocks_m)
        (stripe_id, block_id, NodeId)
        (File, string_id, data_blocks_k, data_blocks_m) => (stripe_id, Placement)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitFile(self, request, context):
        """invoked by client to finalize the file status
        namenode accesses the file metadata structure
        (File, total_blocks, block_ids[])
        (Status)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileMetadata(self, request, context):
        """invoked by client for file metadata query (file retrieval)
        namenode accesses the file metadata structure
        (File)
        (File, stripe_size, data_blocks_k, parity_blocks_m, block_groups)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """invoked by client for deletion
        namenode accesses the file metadata structure
        (File)
        (success, message, block_ids[])
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataNode,
                    request_deserializer=proto_dot_namenode__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.RegisterResponse.SerializeToString,
            ),
            'AllocateBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateBlocks,
                    request_deserializer=proto_dot_namenode__pb2.AllocateBlocksRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.AllocateBlocksResponse.SerializeToString,
            ),
            'CommitFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitFile,
                    request_deserializer=proto_dot_namenode__pb2.CommitFileRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.CommitFileResponse.SerializeToString,
            ),
            'GetFileMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileMetadata,
                    request_deserializer=proto_dot_namenode__pb2.GetFileMetadataRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.GetFileMetadataResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=proto_dot_namenode__pb2.DeleteFileRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.DeleteFileResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_namenode__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=proto_dot_namenode__pb2.ListFilesRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.NameNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.NameNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NameNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/RegisterDataNode',
            proto_dot_namenode__pb2.RegisterRequest.SerializeToString,
            proto_dot_namenode__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/AllocateBlocks',
            proto_dot_namenode__pb2.AllocateBlocksRequest.SerializeToString,
            proto_dot_namenode__pb2.AllocateBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/CommitFile',
            proto_dot_namenode__pb2.CommitFileRequest.SerializeToString,
            proto_dot_namenode__pb2.CommitFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/GetFileMetadata',
            proto_dot_namenode__pb2.GetFileMetadataRequest.SerializeToString,
            proto_dot_namenode__pb2.GetFileMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/DeleteFile',
            proto_dot_namenode__pb2.DeleteFileRequest.SerializeToString,
            proto_dot_namenode__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/SendHeartbeat',
            proto_dot_namenode__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_namenode__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/ListFiles',
            proto_dot_namenode__pb2.ListFilesRequest.SerializeToString,
            proto_dot_namenode__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
