# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import namenode_pb2 as proto_dot_namenode__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/namenode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NameNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDataNode = channel.unary_unary(
                '/proto.NameNodeService/RegisterDataNode',
                request_serializer=proto_dot_namenode__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/proto.NameNodeService/SendHeartbeat',
                request_serializer=proto_dot_namenode__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.AllocateStripe = channel.unary_unary(
                '/proto.NameNodeService/AllocateStripe',
                request_serializer=proto_dot_namenode__pb2.AllocateStripeRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.AllocateStripeResponse.FromString,
                _registered_method=True)
        self.ReportShard = channel.unary_unary(
                '/proto.NameNodeService/ReportShard',
                request_serializer=proto_dot_namenode__pb2.ReportShardRequest.SerializeToString,
                response_deserializer=proto_dot_namenode__pb2.ReportShardResponse.FromString,
                _registered_method=True)


class NameNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDataNode(self, request, context):
        """DataNode registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateStripe(self, request, context):
        """Allocate stripe placement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportShard(self, request, context):
        """Report stored shard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataNode,
                    request_deserializer=proto_dot_namenode__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.RegisterResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=proto_dot_namenode__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.HeartbeatResponse.SerializeToString,
            ),
            'AllocateStripe': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateStripe,
                    request_deserializer=proto_dot_namenode__pb2.AllocateStripeRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.AllocateStripeResponse.SerializeToString,
            ),
            'ReportShard': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportShard,
                    request_deserializer=proto_dot_namenode__pb2.ReportShardRequest.FromString,
                    response_serializer=proto_dot_namenode__pb2.ReportShardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.NameNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.NameNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NameNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/RegisterDataNode',
            proto_dot_namenode__pb2.RegisterRequest.SerializeToString,
            proto_dot_namenode__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/SendHeartbeat',
            proto_dot_namenode__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_namenode__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateStripe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/AllocateStripe',
            proto_dot_namenode__pb2.AllocateStripeRequest.SerializeToString,
            proto_dot_namenode__pb2.AllocateStripeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NameNodeService/ReportShard',
            proto_dot_namenode__pb2.ReportShardRequest.SerializeToString,
            proto_dot_namenode__pb2.ReportShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
