# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/namenode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/namenode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/namenode.proto\x12\x05proto\x1a\x12proto/common.proto\"F\n\x0fRegisterRequest\x12\x1b\n\x04node\x18\x01 \x01(\x0b\x32\r.proto.NodeId\x12\x16\n\x0e\x63\x61pacity_bytes\x18\x02 \x01(\x03\"1\n\x10RegisterResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status\"7\n\x10HeartbeatRequest\x12#\n\theartbeat\x18\x01 \x01(\x0b\x32\x10.proto.Heartbeat\"2\n\x11HeartbeatResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status\"K\n\x15\x41llocateStripeRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x1f\n\x06policy\x18\x02 \x01(\x0b\x32\x0f.proto.ECPolicy\"\x83\x01\n\x16\x41llocateStripeResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status\x12\x1f\n\x06stripe\x18\x02 \x01(\x0b\x32\x0f.proto.StripeId\x12)\n\nplacements\x18\x03 \x03(\x0b\x32\x15.proto.ShardPlacement\"V\n\x12ReportShardRequest\x12#\n\x05shard\x18\x01 \x01(\x0b\x32\x14.proto.ShardMetadata\x12\x1b\n\x04node\x18\x02 \x01(\x0b\x32\r.proto.NodeId\"4\n\x13ReportShardResponse\x12\x1d\n\x06status\x18\x01 \x01(\x0b\x32\r.proto.Status2\xaf\x02\n\x0fNameNodeService\x12\x43\n\x10RegisterDataNode\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponse\x12\x42\n\rSendHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponse\x12M\n\x0e\x41llocateStripe\x12\x1c.proto.AllocateStripeRequest\x1a\x1d.proto.AllocateStripeResponse\x12\x44\n\x0bReportShard\x12\x19.proto.ReportShardRequest\x1a\x1a.proto.ReportShardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.namenode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=51
  _globals['_REGISTERREQUEST']._serialized_end=121
  _globals['_REGISTERRESPONSE']._serialized_start=123
  _globals['_REGISTERRESPONSE']._serialized_end=172
  _globals['_HEARTBEATREQUEST']._serialized_start=174
  _globals['_HEARTBEATREQUEST']._serialized_end=229
  _globals['_HEARTBEATRESPONSE']._serialized_start=231
  _globals['_HEARTBEATRESPONSE']._serialized_end=281
  _globals['_ALLOCATESTRIPEREQUEST']._serialized_start=283
  _globals['_ALLOCATESTRIPEREQUEST']._serialized_end=358
  _globals['_ALLOCATESTRIPERESPONSE']._serialized_start=361
  _globals['_ALLOCATESTRIPERESPONSE']._serialized_end=492
  _globals['_REPORTSHARDREQUEST']._serialized_start=494
  _globals['_REPORTSHARDREQUEST']._serialized_end=580
  _globals['_REPORTSHARDRESPONSE']._serialized_start=582
  _globals['_REPORTSHARDRESPONSE']._serialized_end=634
  _globals['_NAMENODESERVICE']._serialized_start=637
  _globals['_NAMENODESERVICE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
